name: Deploy model to SageMaker

on:
  push:
    branches: [ develop ]
  # repository_dispatch:
  #   types: [ model_registered ]
  # workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      SAGEMAKER_ROLE_ARN: ${{ secrets.SAGEMAKER_ROLE_ARN }}
    steps:
    - uses: actions/checkout@v6.0.1

    - name: Setup python
      uses: actions/setup-python@v6.1.0
      with: 
        python-version: '3.13'

    - name: Install deps
      run: pip install -r requirements.txt mlflow boto3 sagemaker

    #Connect AWS account with OIDC Provider
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.1.1
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::805702559038:role/Github_Actions_EKS_Repo
        
    - name: Deploy from MLflow Registry to SageMaker
      run: |
        python src/register_and_deploy.py --action deploy \
            --mlflow-uri $MLFLOW_TRACKING_URI \
            --sagemaker-role $SAGEMAKER_ROLE_ARN \
            --aws-region $AWS_REGION
